src/LitReview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('accounts/', include('allauth.urls')),
    path('UserFollows/', include('UserFollows.urls', namespace='UserFollows')),
    path('Tickets/', include('Tickets.urls', namespace='Tickets')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/Tickets/urls.py
from django.urls import path
from .views import ticket_review_create_and_list_view , TicketDeleteView, TicketUpdateView

app_name = 'Tickets'

urlpatterns = [
    path('', ticket_review_create_and_list_view, name='main-ticket-view'),
    # path('liked/', like_unlike_post, name='like-ticket-view'),
    path('<pk>/delete/', TicketDeleteView.as_view(), name='Ticket-delete'),
    path('<pk>/update/', TicketUpdateView.as_view(), name='Ticket-update'),
]

src/UserFollows/urls.py
from django.urls import path
from .views import  (my_profile_view, 
                    invites_received_view, 
                    profiles_list_view,
                    invite_profiles_list_view, 
                    ProfileDetailView, 
                    ProfileListView, 
                    send_invatation, 
                    remove_from_friends, 
                    accept_invatation, 
                    reject_invatation,)

app_name = 'UserFollows'
#  Create your views here.
urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invatation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/acctept/', accept_invatation, name='accept-invite'),
    path('my-invites/reject/', reject_invatation, name='reject-invite'),
    
]

src/UserFollows/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q

# Create your models here.
class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = UserFollow.objects.all().exclude(user=sender)
        profile = UserFollow.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)
        available = [profile for profile in profiles if profile not in accepted]
        return available
        

    def get_all_profiles(self, me):
        profiles = UserFollow.objects.all().exclude(user=me)
        return profiles

class UserFollow(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='avatar.png', upload_to='avatars/')
    followed_user = models.ManyToManyField(User, blank=True, related_name='followed_user')
    slug = models.SlugField(unique=True, blank=True)    
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProfileManager()
    def __str__(self):
        return f"{self.user.username}"

    def get_absolute_url(self):
        return reverse("UserFollows:profile-detail-view", kwargs={"slug": self.slug})
    
    def get_followers(self):
        return self.followed_user.all()

    def get_followers_no(self):
        return self.followed_user.all().count()

    def get_Ticket_no(self):
        return self.tickets.all().count() #non resolue

    def get_all_authors_Ticket(self):
        return self.tickets.all()

    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug=="":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                ex = UserFollow.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_code()))
                    ex = UserFollow.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)

    
STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted'))

class RelationshipManager(models.Manager):
    def invatations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs    

 
class Relationship(models.Model):
    sender = models.ForeignKey(UserFollow, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(UserFollow, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)   
    objects = RelationshipManager()


    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

src/UserFollows/forms.py
from django import forms
from .models import UserFollow

class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = UserFollow
        fields = ('first_name', 'last_name',  'avatar')

src/UserFollows/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import UserFollow, Relationship
from .forms import ProfileModelForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

@login_required
def my_profile_view(request):
    profile = UserFollow.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True

    context = {
        'profile': profile,
        'form': form,
        'confirm': confirm,
    }

    return render(request, 'UserFollows/myprofil.html', context)

@login_required
def invites_received_view(request):
    profile = UserFollow.objects.get(user=request.user)
    qs = Relationship.objects.invatations_received(profile)
    results = list(map(lambda x: x.sender, qs))
    is_empty = False
    if len(results) == 0:
        is_empty = True

    context = {
        'qs': results,
        'is_empty': is_empty,
    }

    return render(request, 'UserFollows/my_invites.html', context)

@login_required
def accept_invatation(request):
    if request.method=="POST":
        pk = request.POST.get('profile_pk')
        sender = UserFollow.objects.get(pk=pk)
        receiver = UserFollow.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('UserFollows:my-invites-view')

@login_required
def reject_invatation(request):
    if request.method=="POST":
        pk = request.POST.get('profile_pk')
        receiver = UserFollow.objects.get(user=request.user)
        sender = UserFollow.objects.get(pk=pk)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('UserFollows:my-invites-view')

@login_required
def invite_profiles_list_view(request):
    user = request.user
    qs = UserFollow.objects.get_all_profiles_to_invite(user)
    context = {'qs': qs}
    return render(request, 'UserFollows/to_invite_list.html', context)

@login_required
def profiles_list_view(request):
    user = request.user
    qs = UserFollow.objects.get_all_profiles(user)
    context = {'qs': qs}
    return render(request, 'UserFollows/profile_list.html', context)

class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = UserFollow
    template_name = 'UserFollows/detail.html'

    # def get_object(self):
    #     slug = self.kwargs.get('slug')
    #     profile = UserFollow.objects.get(slug=slug)
    #     return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = UserFollow.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context['Tickets'] = self.get_object().get_all_authors_Ticket()
        context['len_posts'] = True if len(self.get_object().get_all_authors_Ticket()) > 0 else False
        return context

class ProfileListView(LoginRequiredMixin, ListView):
    model = UserFollow
    template_name = 'UserFollows/profile_list.html'
    # context_object_name = 'qs'

    def get_queryset(self):
        qs = UserFollow.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = UserFollow.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True

        return context

@login_required
def send_invatation(request):
    if request.method=='POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = UserFollow.objects.get(user=user)
        receiver = UserFollow.objects.get(pk=pk)
        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('UserFollows:my-profile-view')
    
@login_required
def remove_from_friends(request):
    if request.method=='POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = UserFollow.objects.get(user=user)
        receiver = UserFollow.objects.get(pk=pk)
        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))

    return redirect('UserFollows:my-profile-view')

    
    

src/UserFollows/templates/UserFollows/detail.html
{% extends 'base.html' %}

{% block title %}
profile detail
{% endblock title %}

{% block content %}
<div class="ui grid">
    <br>
    <div class="row">
        <div class="four wide column">
            <img class="ui medium rounded image"  alt="" src={{object.avatar.url}}>
            <h1>{{object.user}}</h1>
            <div class="ui vertical fluid menu">
                <div class="item">
                    Tickets
                    <div class="ui label">{{ object.get_Ticket_no }}</div>
                </div>
                <div class="item">
                    Followers
                    <div class="ui label">{{ object.get_followers_no }}</div>
                </div>
            </div>

            {% if object.user not in rel_receiver and object.user not in rel_sender %}
                <form action="{% url 'UserFollows:send-invite' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                </form>
            {% endif %}

            {% if object.user in rel_receiver and request.user not in object.followed_user.all %}
                <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
            {% endif %}

            {% if request.user in object.followed_user.all %}
                <form action="{% url 'UserFollows:remove-friend' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                </form>
            {% endif %}

        </div>
        <div class="twelve wide column">
            {% if len_posts %}
                {% for ticket in Tickets %}
                    <div class="segment ui fluid">
                        {{ticket.Description}}
                    </div>
                {% endfor %}
            {% else %}
                <h1>No Ticket of this user ...</h1>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

src/UserFollows/templates/UserFollows/my_invites.html
{% extends 'base.html' %}

{% block title %}
my invites
{% endblock title %}

{% block content %}

    {% if is_empty %}
        <h1>No invitations here..</h1>
    {% endif %}
 profiles
    {% for obj in qs %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.avatar.url}}>
                    </div>
                    
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <br>
                        <a href="">
                            <button class="ui primary button w-big mb-5">See profile</button>
                        </a>
                        <form action="{% url 'UserFollows:accept-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui positive basic button w-big mb-5">
                                <i class="check icon"></i>
                                Accept invite
                            </button>
                        </form>
                         <form action="{% url 'UserFollows:reject-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button w-big mb-5">
                                <i class="close icon"></i>
                                Reject invite
                            </button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    {% endfor %}

{% endblock content %}

src/UserFollows/templates/UserFollows/myprofil.html
{% extends 'base.html' %}

{% block title %}
my profile
{% endblock title %}

{% block content %}

<!-- MODAL -->
<div class="ui modal mymodal">
  <i class="close icon"></i>
  <div class="header">
    Update your Profile
  </div>
  <div class="image content">
    <div class="ui medium image">
      <img src="{{profile.avatar.url}}" alt="">
    </div>
    <div class="description">
      <div class="ui header">Provide some additional/newest info about you </div>
     <form action="" method="POST" class="ui form" enctype='multipart/form-data'>
        {% csrf_token %}
        {{form.as_p}}
    </div>
  </div>
  <div class="actions">
    <button type='submit' class="ui positive right labeled icon button">
      Update
      <i class="checkmark icon"></i>
    </button>
    </form>
  </div>
</div>

<div class="ui segment">
    {% if confirm %}
        <div class="ui green message">Your profile has been updated</div>
    {% endif %}
    <h3>my profile: {{request.user}}</h3>
    <div class="ui grid">
        <div class='row'>
            <div class='six wide column'>
                <img class="ui medium rounded image" src={{profile.avatar.url}}>
                <div class="row mt-5">
                    <button class='ui secondary button' id='modal-btn'>Update your profile</button>
                </div>
            </div>
            <div class="ten wide column">
                <table class="ui table">
                    <tbody>
                        <tr>
                            <td>username</td>
                            <td>{{profile.user}}</td>
                        </tr>
                        <tr>
                            <td>first name</td>
                            <td>{{profile.first_name}}</td>
                        </tr>
                        <tr>
                            <td>last name</td>
                            <td>{{profile.last_name}}</td>
                        </tr>
        
                        <tr>
                            <td>number of followers</td>
                            <td>{{profile.get_followers_no}}</td>
                        </tr>
                        <tr>
                            <td>followers</td>
                            <td>
                                <ul>
                                    {% for follower in profile.get_followers %}
                                        <li>{{follower}}</li>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>number of posts</td>
                            <td>{{profile.get_Ticket_no}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

src/UserFollows/templates/UserFollows/profile_list.html
{% extends 'base.html' %}

{% block title %}
all UserFollows
{% endblock title %}

{% block content %}

    {% if is_empty %}
        <h1>No UserFollows to interact with</h1>
    {% endif %}

    {% for obj in object_list %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" alt="" src={{obj.avatar.url}}>
                    </div>

                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <a href={{obj.get_absolute_url}}><button class="ui primary button mb-5 w-big">See profile</button></a>
                        <br>

                        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                            <form action="{% url 'UserFollows:send-invite' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                            </form>
                         {% endif %}

                        {% if obj.user in rel_receiver and request.user not in obj.followed_user.all %}
                            <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                        {% endif %}

                        {% if request.user in obj.followed_user.all %}
                        <form action="{% url 'UserFollows:remove-friend' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                        </form>
                        {% endif %}
                    </div>

                </div> 
            </div> 
        </div>
    {% endfor %}
{% endblock content %}

src/UserFollows/templates/UserFollows/to_invite_list.html
{% extends 'base.html' %}

{% block title %}
invite friends
{% endblock title %}

{% block content %}

    <div class="ui container">
        <div class="center menu">
            <div class="item">
                <form action="" method="GET">
                    <div class="ui fluid action  left icon input">
                        <input type="text" placeholder="Search...">
                        <i class="search icon"></i>
                        <div class="ui button">Search</div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <ul>
        {% for item in qs %}
            <li>{{item}}</li>
        {% endfor %}
    </ul>
{% endblock content %}