src/LitReview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('accounts/', include('allauth.urls')),
    path('UserFollows/', include('UserFollows.urls', namespace='UserFollows')),
    path('Tickets/', include('Tickets.urls', namespace='Tickets')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/Tickets/urls.py
from django.urls import path
from .views import ticket_review_create_and_list_view , TicketDeleteView, TicketUpdateView

app_name = 'Tickets'

urlpatterns = [
    path('', ticket_review_create_and_list_view, name='main-ticket-view'),
    # path('liked/', like_unlike_post, name='like-ticket-view'),
    path('<pk>/delete/', TicketDeleteView.as_view(), name='Ticket-delete'),
    path('<pk>/update/', TicketUpdateView.as_view(), name='Ticket-update'),
]

src/UserFollows/urls.py
from django.urls import path
from .views import  (my_profile_view, 
                    invites_received_view, 
                    profiles_list_view,
                    invite_profiles_list_view, 
                    ProfileDetailView, 
                    ProfileListView, 
                    send_invatation, 
                    remove_from_friends, 
                    accept_invatation, 
                    reject_invatation,)

app_name = 'UserFollows'
#  Create your views here.
urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invatation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/acctept/', accept_invatation, name='accept-invite'),
    path('my-invites/reject/', reject_invatation, name='reject-invite'),
    
]

src/templates/main/home.html
{% extends 'base.html' %}

{% block title %}
home
{% endblock title %}

{% block content %}
<h1> Bienvenu Sur LITReview </h1>
<br>
<h3></h3>
{% endblock content %}

{% block scripts %}

{% endblock scripts %}

src/templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'Tickets:main-ticket-view' as path_to_posts %}
{% url 'UserFollows:my-profile-view' as path_to_my_profile %}
{% url 'UserFollows:my-invites-view' as path_to_my_invites %}
{% url 'UserFollows:invite-profiles-view' as path_to_invites %}
{% url 'UserFollows:all-profiles-view' as path_to_all_profiles %}

<div class="ui inverted menu nav mb-7">
  <div class="ui container">
    <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
        <h3>LITReview</h3>
    </a>

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
            Flux
        </a>
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Abonnements
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                        Tous les  profiles
                    </a>
                    <a href="{{path_to_invites}}" class="{% if request.path == path_to_invites %}active{% endif %} item">
                        envoyer demande
                    </a>

                    <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                        demandes Abonnements &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                    </a>
                </div>
             </div>
        </div>
            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                <img src={{picture.url}} class="ui avatar image" alt="">&nbsp;
                 {{ request.user }}
            </a>

            <a href="{% url 'account_logout' %}" class="ui item">
                se déconnecter
            </a>
        {% else %}
        <a href="{% url 'account_login' %}" class="ui item">
                se connecter
            </a>
        {% endif %}
    </div>
  </div>
</div>