src/LitReview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('accounts/', include('allauth.urls')),
    path('UserFollows/', include('UserFollows.urls', namespace='UserFollows')),
    path('Tickets/', include('Tickets.urls', namespace='Tickets')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/Tickets/urls.py
from django.urls import path
from .views import ticket_review_create_and_list_view , TicketDeleteView, TicketUpdateView

app_name = 'Tickets'

urlpatterns = [
    path('', ticket_review_create_and_list_view, name='main-ticket-view'),
    # path('liked/', like_unlike_post, name='like-ticket-view'),
    path('<pk>/delete/', TicketDeleteView.as_view(), name='Ticket-delete'),
    path('<pk>/update/', TicketUpdateView.as_view(), name='Ticket-update'),
]

src/Tickets/models.py
from django.db import models
from django.core.validators import  MinValueValidator, MaxValueValidator
from UserFollows.models import UserFollow
# Create your models here.

class Ticket(models.Model):
    Title = models.CharField(max_length=128)
    Description = models.TextField()
    author = models.ForeignKey(UserFollow, on_delete=models.CASCADE, related_name='tickets')
    image = models.ImageField(upload_to='tickets',null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.Title}-{str(self.Description[:20])}"
        # return str(self.Description[:20])


    def num_reviews(self):
        return self.review_set.all().count()

    class Meta:
        ordering = ('-created',)

class Review(models.Model):
    user = models.ForeignKey(UserFollow, on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    headline = models.CharField(max_length=128)
    body = models.CharField(max_length=8192, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)

    

src/Tickets/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import UserFollow
from Tickets.models import Ticket
from .form import TicketModelForm, ReviewModelForm
from django.views.generic import UpdateView, DeleteView
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

@login_required
def ticket_review_create_and_list_view(request):
    qs = Ticket.objects.all()
    userfollow = UserFollow.objects.get(user=request.user)
    t_form = TicketModelForm()
    r_form = ReviewModelForm()
    ticket_added = False
    # userfollow = UserFollow.objects.get(user=request.user)

    if 'submit_t_form' in request.POST:
        # print(request.POST)
        t_form = TicketModelForm(request.POST, request.FILES)
        if t_form.is_valid():
            instance = t_form.save(commit=False)
            instance.author = userfollow
            instance.save()
            t_form = TicketModelForm()
            ticket_added = True

    if 'submit_r_form' in request.POST:
        r_form = ReviewModelForm(request.POST)
        if r_form.is_valid():
            instance = r_form.save(commit=False)
            instance.user = userfollow
            instance.ticket = Ticket.objects.get(id=request.POST.get('ticket_id'))
            instance.save()
            r_form = ReviewModelForm()

    context = {
        'qs': qs,
        'userfollow': userfollow,
        't_form': t_form,
        'r_form': r_form,
        'ticket_added': ticket_added,
    }
    return render(request, 'Tickets/main.html', context)
 
class TicketDeleteView(LoginRequiredMixin, DeleteView): 
    model = Ticket
    template_name = 'Tickets/confirm_del.html'
    success_url = '/Tickets/'
    
    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Ticket.objects.get(pk=pk)
        if not obj.author.user == self.request.user:
            messages.warning(self.request, 'You need to be the author of the post in order to delete it')
        return obj

class TicketUpdateView(LoginRequiredMixin, UpdateView):
    form_class = TicketModelForm
    model = Ticket
    template_name = 'Tickets/update.html'
    success_url = '/Tickets/'


    def form_valid(self, form):
        profile = UserFollow.objects.get(user=self.request.user)
        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None, "You need to be the author of the post in order to update it")
            return super().form_invalid(form)

src/Tickets/templates/Tickets/confirm_del.html
{% extends 'base.html' %}

{% block title %}
delete post
{% endblock title %}

{% block content %}

    {% if messages %}
        {% for message in messages %}
            {% if 'warning' in message.tags %}
                <div class='ui negative message'>
                    <div class="header">
                        {{message}}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    {% if not messages %}
        <div class="ui segment">
            <h3>Delete post?</h3>
            <form action="" method="POST">
                {% csrf_token %}
                <p>Are you sure you want to delete the post?</p>
                <button type='submit'>Submit</button>
            </form>
        </div>
    {% endif %}

{% endblock content %}

src/Tickets/templates/Tickets/main.html
{% extends 'base.html' %}

{% block title %}main page{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="fifteen wide column">
       <div class="ui grid">
           <div class="eight wide column">
                <div class="ui segment" >
                    &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;
                    &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;
                    &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;
                    <button class="cmt_btn1 ui button mb-5">Demander Critique </button>
                    <div class="comment-box1">
                        <div class="ui segment">
                            {% if ticket_added %}
                                <div class="ui green message">Ticket added</div>
                            {% endif %}
                            <form action="" method="POST" class='ui form' enctype="multipart/form-data" id="sh">
                                {% csrf_token %}
                                {{t_form}}
                                <button type='submit' name="submit_t_form" class="ui positive button w-full mt-5">Envoyer</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="eight wide column">
                <div class="ui segment">
                    &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;
                    &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;
                    &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;
                    <button class="cmt_btn2 ui button mb-5">Creer Critique </button>
                    <div class="comment-box2">
                        <form action="" method="POST" class='ui form' enctype="multipart/form-data">
                            {% csrf_token %}
                            <p >Article/livre</p>
                            {{t_form}} <br><br><hr>
                            <p >Critique</p>
                            {{r_form}}
                            <button type='submit' name="submit_t_form" class="ui positive button w-full mt-5">Envoyer</button>
                        </form>
                    </div>
                </div> 
            </div>
        </div>
        {% for obj in qs %}
        <div class="ui fluid card">
            <div class="content">
                <div class="right floated meta">
                    <div class="ui grid">
                         <div class="row">
                            {% ifequal request.user obj.author.user %}
                                <a href="{% url 'Tickets:Ticket-update' obj.pk %}"><button class="ui button bwhite-lg ">Modifier</button></a>
                                <a href="{% url 'Tickets:Ticket-delete' obj.pk %}"><button class="ui button bwhite-lg ">Supprimer</button></a>
                            {% endifequal %}
                        </div>
                    </div>
                </div>
                <img class="ui avatar image" src={{obj.author.avatar.url}} alt=""> 
                {{ obj.author.user }} -{{ obj.created}}  
            </div>
            <div class="ui fluid image">
                {% if obj.image %}
                    <img src={{obj.image.url}} alt="">
                {% endif %}
            </div>
            <div class="content">
                <p>Book Title:&nbsp; &nbsp;{{obj.Title}}</p>
                <p>Book Description:&nbsp; &nbsp;{{ obj.Description }} </p>
                <i class="comment icon"></i>
                <span> {{ obj.num_reviews }} Critique</span>
            </div>

            <div class="extra content">
                <div class="mb-5">
                </div>
                <button class="cmt_btn ui button mb-5">Afficher/Cacher Critique </button>
                <div class="comment-box">
                {% if obj.review_set.all %}
                    {% for r in obj.review_set.all %}
                        <div class="ui segment mb-5">
                            <img class="ui avatar image" src={{r.user.avatar.url}} alt="">
                            <span> {{ r.user }}</span> <br>
                                <form class="rate-form" action="" method="POST" id="{{object.id}}">
                                    {% csrf_token %}
                                    {{ r.headline }} &nbsp;: {{r.rating}}
                                    <button type="submit" class="fa fa-star fa-3x my-btn" id="first"></button>
                                    <button type="submit" class="fa fa-star fa-3x my-btn" id="second"></button>
                                    <button type="submit" class="fa fa-star fa-3x my-btn" id="third"></button>
                                    <button type="submit" class="fa fa-star fa-3x my-btn" id="fourth"></button>
                                    <button type="submit" class="fa fa-star fa-3x my-btn" id="fifth"></button>
                                    &nbsp; 
                                </form>
                                <br>
                                <div id="confirm-box"></div>
                            <div class='mt-5'>{{ r.body }}</div>  
                            <p>{{request.author}}</p>
                        </div>
                    {% endfor %}
                {% endif %}  
                </div><br><br>
                <form action="" method="POST"class='ui fluid form'>
                    <button class="ui button " style="background-color:#bbc5ce;">Creer Critique </button> <br>
                    {% csrf_token %}
                    <input type="hidden" name="ticket_id" value={{obj.id}}>
                    {{ r_form }}
                    <button type="submit" name="submit_r_form" class="ui primary button mt-5 w-full">Send</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="one wide column">

    </div>
</div>

<style>
    .checked {
            color: red;
        }

    .my-btn {
            background-color: inherit !important;
            border: 0 !important;
            
        }
    .fa{
            font-size: 1.5em;
        }
</style>
{% endblock content %}


{% block scripts %} 
    <script>
        $( document ).ready(function() {
            let display = false
            $(".cmt_btn").click(function () {
                if (display===false) {
                    $(this).next(".comment-box").show("slow");
                    display=true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display=false
                }  
            });
        });

        $( document ).ready(function() {
            let display = false
            $(".cmt_btn1").click(function () {
                if (display===false) {
                    $(this).next(".comment-box1").hide("fast");
                    display=true
                } else {
                    $(this).next(".comment-box1").show("fast");
                    display=false
                }  
            });
        });

        $( document ).ready(function() {
            let display = false
            $(".cmt_btn2").click(function () {
                if (display===false) {
                    $(this).next(".comment-box2").hide("fast");
                    display=true
                } else {
                    $(this).next(".comment-box2").show("fast");
                    display=false
                }  
            });
        });



        // ----------------------------------------scrip rating-------------------


// get all the stars
const one = document.getElementById('first')
const two = document.getElementById('second')
const three = document.getElementById('third')
const four = document.getElementById('fourth')
const five = document.getElementById('fifth')

// get the form, confirm-box and csrf token
const form = document.querySelector('.rate-form')
const confirmBox = document.getElementById('confirm-box')
const csrf = document.getElementsByName('csrfmiddlewaretoken')

const handleStarSelect = (size) => {
    const children = form.children
    console.log(children[0])
    for (let i=0; i < children.length; i++) {
        if(i <= size) {
            children[i].classList.add('checked')
        } else {
            children[i].classList.remove('checked')
        }
    }
}

const handleSelect = (selection) => {
    switch(selection){
        case 'first': {
            handleStarSelect(1)
            return
        }
        case 'second': {
            handleStarSelect(2)
            return
        }
        case 'third': {
            handleStarSelect(3)
            return
        }
        case 'fourth': {
            handleStarSelect(4)
            return
        }
        case 'fifth': {
            handleStarSelect(5)
            return
        }
        default: {
            handleStarSelect(0)
        }
    }

}

const getNumericValue = (stringValue) =>{
    let numericValue;
    if (stringValue === 'first') {
        numericValue = 1
    } 
    else if (stringValue === 'second') {
        numericValue = 2
    }
    else if (stringValue === 'third') {
        numericValue = 3
    }
    else if (stringValue === 'fourth') {
        numericValue = 4
    }
    else if (stringValue === 'fifth') {
        numericValue = 5
    }
    else {
        numericValue = 0
    }
    return numericValue
}

if (one) {
    const arr = [one, two, three, four, five]

    arr.forEach(item=> item.addEventListener('mouseover', (event)=>{
        handleSelect(event.target.id)
    }))

    arr.forEach(item=> item.addEventListener('click', (event)=>{
        // value of the rating not numeric
        const val = event.target.id
        
        let isSubmit = false
        form.addEventListener('submit', e=>{
            e.preventDefault()
            if (isSubmit) {
                return
            }
            isSubmit = true
            const val_num = getNumericValue(val)
        })
    }))
}
</script>
{% endblock scripts %}

src/Tickets/templates/Tickets/update.html
{% extends 'base.html' %}

{% block title %}
update post
{% endblock title %}

{% block content %}
    <div class='ui segment'>
        <h3>Update post</h3>
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <button type='submit' class="ui button primary mt-5">Update</button>
        </form>
    </div>
{% endblock content %}